version: "3.8"

services:
  postgres:
    container_name: multi-tenancy-db
    image: postgres:14.4
    ports:
      - "5432:5432"
    volumes:
      - tenancy-pgdata:/var/lib/postgresql/data
    env_file:
      - docker-compose.env

volumes:
  tenancy-pgdata: